# Generated by Django 4.0.4 on 2022-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBMS_basics', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
