# Generated by Django 4.0.4 on 2022-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBMS_basics', '0010_rename_billinginformation_order_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
